[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Compilation settings
solc = "0.8.19"
evm_version = "paris"

# Testing settings
verbosity = 2

# Formatter settings
line_length = 120
tab_width = 4
bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
